name: bronze-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.*
  - jupyterlab=1.1.*
  - matplotlib=3.1.*
  - python=3.7.*
  - pip=19.2.*
  - pip:
    - qiskit==0.13.*
    - qiskit-terra[visualization]
